CUDA_VISIBLE_DEVICES=0 python yoloxyz/train.py \
    --basemodel 'v9' \
    --weights weights/yolov9-c.pt \
    --cfg yoloxyz/cfg/architecture/yolov9-c.yaml \
    --hyp yoloxyz/cfg/hyp/hyp.scratch-high-v9.yaml \
    --data yoloxyz/cfg/data/food.yaml \
    --name finetune_v9 \
    --batch 4 \
    --epochs 2 \
    --imgsz 640 \
    --device 0 \
    --workers 2 \
    --close-mosaic 15 \
    --sync-bn \
    --min-items 0 \
    --detect-layer 'DualDDetect'